### PR TITLE
Add support for getting shell in termux (on android)

### LINKED ISSUE #3: Android termux support
When GOOS is 'android',
(and we are running under termux)

`shell := os.Getenv("SHELL")`

### PR DESCRIPTION
**Pull request by earboxer**
Close #3

Tested with aerc.

### CODE REVIEW

**Comment by riywo** [comment]
Hi,

Do you have a document or something that explains this is the right way to get it?

**Comment by earboxer** [comment]
> Use chsh from termux-tools to change your login shell. Currently Termux supports bash, fish, tcsh, zsh and a few other shells. 

https://wiki.termux.com/wiki/Shells

https://github.com/termux/termux-packages/blob/master/packages/termux-tools/chsh is the source code for chsh

It creates a symlink to your shell in `~/.termux/shell` (so I guess we could check that instead of checking $SHELL)

**Comment by earboxer** [comment]
However, this symlink can be deleted by the user, in which case, termux will fall back on bash:

Termux exports the SHELL variable as follows (in the [`login` script](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/login)):
```sh
if [ -G ~/.termux/shell ]; then
	export SHELL="`realpath ~/.termux/shell`"
else
	for file in @TERMUX_PREFIX@/bin/bash @TERMUX_PREFIX@/bin/sh /system/bin/sh; do
		if [ -x $file ]; then
			export SHELL=$file
			break
		fi
	done
fi
```

([@TERMUX_PREFIX@](https://wiki.termux.com/wiki/Differences_from_Linux) is exported as $PREFIX)

The most foolproof way to get the shell would be to re-implement the code snippet above, but that just makes us reliant on a different exported variable: $PREFIX. It also makes our code potentially more brittle: termux in the future might implement different fallback shells or storage locations.

So, I think using $SHELL would be the best (and we would just count on users not to shoot themselves in the foot by overwriting that exported variable).

**Comment by earboxer** [comment]
@riywo did you see this? Note that the code snippet as given above has not changed.
Termux is **the** open source terminal emulator on Android, providing golang as a package.
(Please merge this)

**Pull request merged**
